name: Compute Tag
description: Compute the next tag based on the previous tag and the version scheme
author: Craig Day
branding:
  color: purple
  icon: tag

runs:
  using: node12
  main: action.js

inputs:
  repository:
    description: The fully qualified repository, i.e. owner/repo. Usually from `{{ github.repository }}`.
    required: true
  github_token:
    description: A Github token for the repo, usually `{{ github.token }}`.
    required: true
  version_scheme:
    description: The versioning scheme to use. Currently only supports `continuous` or `semantic`.
    required: false
    default: semantic
  version_type:
    description: >
      Is this a major, minor, patch, or prerelease bump? For continuous versioning, only
      `prerelease` means anything.
    required: false
    default: prerelease
  prerelease_suffix:
    description: What to annotate a prerelease version tag with.
    required: false
    default: 'pre'
  include_build_number:
    description: >
      If continuous versioning, whether to append the build number to the end of prerelease tags.
    required: false
    default: 'false'

outputs:
  next_tag:
    description: The computed next tag to be created
