name: Compute Tag
description: Compute the next tag based on the previous tag and the version scheme
author: Craig Day
branding:
  color: purple
  icon: tag

runs:
  using: node12
  main: action.js

inputs:
  repository:
    description: The fully qualified repository, i.e. owner/repo. Usually from `{{ github.repository }}`.
    required: true
  github_token:
    description: A Github token for the repo, usually `{{ github.token }}`.
    required: true
  version_scheme:
    description: The versioning scheme to use. Currently only supports `continuous` or `semantic`.
    required: false
    default: continuous
  version_type:
    description: If using semantic versioning, is this a major, minor, or patch bump?
    required: false
    default: patch
  prerelease:
    description: Treat this version as prerelease instead of a regular release.
    required: false
    default: 'false'
  prerelease_suffix:
    description: What to annotate a prerelease version tag with.
    required: false
    default: 'pre'

outputs:
  next_tag:
    description: The computed next tag to be created
