name: Example Runs

on: push

jobs:
  example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scheme:
          - continuous
          - semantic
        type:
          - null
          - major
          - minor
          - patch
          - prerelease
    steps:
      - uses: actions/checkout@v2

      - id: compute_tag
        uses: ./
        with:
          github_token: ${{ github.token }}
          version_scheme: ${{ matrix.scheme }}
          version_type: ${{ matrix.type }}

      - name: print out computed tag
        run: echo "The next computed tag is $TAG"
        env:
          TAG: ${{ steps.compute_tag.outputs.next_tag }}
